### PR TITLE
[semver:minor] --filters -> --parameter-filters

### PR DESCRIPTION
**Pull request by chrisstephenmiller**
### Checklist

- [X] All new jobs, commands, executors, parameters have descriptions
- [X] Examples have been added for any significant new features
- [x] README has been updated, if necessary

### Motivation, issues

https://github.com/CircleCI-Public/aws-parameter-store-orb/issues/12

### Description

Update use of "--filters" option to "--parameter-filters" per AWS documentation: 
https://docs.aws.amazon.com/cli/latest/reference/ssm/describe-parameters.html

### CODE REVIEW

**Comment by stringbeans** [comment]
just recently ran into this issue! what can we do to get this PR moving?

**Comment by stringbeans** [comment]
i actually think there's a bug with the `--no-paginate` flag... 

1. it does not actually remove the pagination. from my tests, adding the `--no-paginate` flag will actually **paginate** the results (lol)
2. using the deprecated `--filters` flag actually works if you remove `--no-paginate`

**Comment by chrisstephenmiller** [comment]
Yes, it also works by removing the --no-paginate flag. Since the AWS docs indicate "--filters" is deprecated and should be replaced by "--parameter-filters," it seemed like the more forward looking solution. 

I'm sure multiple comments on the issue will speed things along :)

**Comment by chrisstephenmiller** [comment]
@KyleTryon can you review?

**Comment by chrisstephenmiller** [comment]
@gmemstr @KyleTryon any progress?

**Review by gmemstr — APPROVED** [review]
LGTM!

**Pull request merged**
